name: Security Scan

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    paths-ignore:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified
